version: '3'

services:
  server:
    build:
      context: ./.docker/nginx
    volumes:
      - ./:/var/www:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./var/log:/var/log
    depends_on:
      - php
    ports:
      - "8081:80"


  php:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www:cached

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./database_data:/var/lib/postgresql/data:rw
