version: '3'

services:
  postgres_panier:
    image: postgres:16
    container_name: postgres_panier
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - ./.docker/database_data:/var/lib/postgresql/data:rw

  server:
    build:
      context: ./.docker/nginx
    volumes:
      - ./:/var/www:cached
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./var/log:/var/log
    depends_on:
      - php
    ports:
      - "8081:80"

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - ./:/var/www:cached
    command: php bin/console doctrine:migrations:migrate --no-interaction
    depends_on:
      postgres_panier:
        condition: service_started