name: CI

on:
  push:
    branches:
      - main

jobs:
  run-ci:
    runs-on: ubuntu-latest

    services:
      postgres_panier:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Composer Install
        run: composer install

      - name: Build
        run: docker compose -f compose.ci.yaml up --build -d

      - name: Test
        run: docker compose -f compose.ci.yaml exec test vendor/bin/phpunit

      - name: Shutdown containers
        run: docker compose -f compose.ci.yaml down
